apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-frontend-deploy
  labels:
    app: msa-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-frontend
  template:
    metadata:
      name: msa-frontend
      labels:
        app: msa-frontend
    spec:
      containers:
        - name: msa-frontend
          image: sun12wook11/msa-frontend

          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: USER_SRV_URL
              value: 192.168.56.1:31231 # 서버주소:노드포트
            - name: PRODUCT_SRV_URL
              value: 192.168.56.1:31232 # 서버주소:노드포트
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-usersrv-deploy
  labels:
    app: msa-usersrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-usersrv
  template:
    metadata:
      name: msa-usersrv
      labels:
        app: msa-usersrv
    spec:
      containers:
        - name: msa-usersrv
          image: sun12wook11/msa-usersrv
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: CORS_ORIGINS
              value: 192.168.56.1:31230 # 서버주소:노드포트
---
apiVersion: v1
kind: Service
metadata:
  name: msa-frontend-svc
spec:
  selector:
    app: msa-frontend
  type: NodePort
  ports:
    - nodePort: 31230
      port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: msa-usersrv-svc
spec:
  selector:
    app: msa-usersrv
  type: NodePort
  ports:
    - nodePort: 31231
      port: 8000
      protocol: TCP
      targetPort: 8000
---